### ISSUE TITLE
What is BReLU?

### ISSUE THREAD

**Issue by sriharsha0806** [anokland/resnet-brelu#1]
Can you let me know what is Bipolar ReLU and how it is helping in increasing accuracy? and also what do you mean by run1, run2, run3? What is the computational cost?

**Comment by anokland** [comment]
Take a look at this paper: https://openreview.net/forum?id=BkoXnkWAb
The table contains several runs to estimate mean av standard deviation.

2018-02-11 17:27 GMT+01:00 sriharsha annamaneni <notifications@github.com>:
